### ISSUE TITLE
[MDEP-564] NPE on maven 3.5.0

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#1000]
**[Michael Dikman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=archmisha)** opened **[MDEP-564](https://issues.apache.org/jira/browse/MDEP-564?redirect=false)** and commented

When using get goal on maven 3.5.0 getting NPE.
Works fine on maven 3.3.9

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.0:get (default-cli) on project standalone-pom: Execution default-cli of goal org.apache.maven.plugins:maven-dependency-plugin:3.0.0:get failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.0:get (default-cli) on project standalone-pom: Execution default-cli of goal org.apache.maven.plugins:maven-dependency-plugin:3.0.0:get failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-dependency-plugin:3.0.0:get failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.NullPointerException
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:370)
        at org.apache.maven.shared.dependencies.resolve.internal.Maven31DependencyResolver.resolveDependencies(Maven31DependencyResolver.java:227)
        at org.apache.maven.shared.dependencies.resolve.internal.Maven31DependencyResolver.resolveDependencies(Maven31DependencyResolver.java:90)
        at org.apache.maven.shared.dependencies.resolve.internal.DefaultDependencyResolver.resolveDependencies(DefaultDependencyResolver.java:81)
        at org.apache.maven.plugins.dependency.GetMojo.execute(GetMojo.java:226)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

---

**Affects:** 3.0.0

2 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Trying to reproduce this. Having my local nexus working as well...created an artifact with appropriate coordinates (you are using no classifier which means you have either created the artifact via assembly-plugin and appendassemblyId:false or via build-helper-maven-plugin)..

```
~/ws-git/javaee/x (master *)$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/local/maven
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

Calling Maven via the following:

```
mvn org.apache.maven.plugins:maven-dependency-plugin:3.0.0:get -Dartifact=com.soebes.examples.j2ee:assembly:LATEST:tar.gz -DrepoUrl=http://localhost:8081/nexus/content/repositories/releases/ -Dmaven.repo.local=$HOME/.m2/repository
```

The result is:

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.0.0:get (default-cli) @ standalone-pom ---
[INFO] Resolving com.soebes.examples.j2ee:assembly:tar.gz:LATEST with transitive dependencies
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/maven-metadata.xml (422 B at 4.5 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/maven-metadata.xml (958 B at 74 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/assembly-3.4.6-20170427.203600-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/assembly-3.4.6-20170427.203600-1.pom (1.7 kB at 169 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/parent/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/parent/3.4.6-SNAPSHOT/maven-metadata.xml (607 B at 51 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/parent/3.4.6-SNAPSHOT/parent-3.4.6-20170427.203558-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/parent/3.4.6-SNAPSHOT/parent-3.4.6-20170427.203558-1.pom (3.4 kB at 338 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/maven-metadata.xml (780 B at 56 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/webgui-3.4.6-20170427.203559-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/webgui-3.4.6-20170427.203559-1.pom (808 B at 58 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/maven-metadata.xml (781 B at 49 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/service-3.4.6-20170427.203559-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/service-3.4.6-20170427.203559-1.pom (1.5 kB at 85 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/maven-metadata.xml (788 B at 46 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/service-client-3.4.6-20170427.203558-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/service-client-3.4.6-20170427.203558-1.pom (647 B at 59 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/maven-metadata.xml (780 B at 46 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/domain-3.4.6-20170427.203558-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/domain-3.4.6-20170427.203558-1.pom (576 B at 44 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/maven-metadata.xml (1.4 kB at 78 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/shade-3.4.6-20170427.203559-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/shade-3.4.6-20170427.203559-1.pom (2.1 kB at 189 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/assembly-3.4.6-20170427.203600-1.tar.gz
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/webgui-3.4.6-20170427.203559-1.war
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/service-3.4.6-20170427.203559-1.jar
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/service-client-3.4.6-20170427.203558-1.jar
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/domain-3.4.6-20170427.203558-1.jar
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/domain-3.4.6-20170427.203558-1.jar (3.1 kB at 172 kB/s)
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/service-3.4.6-20170427.203559-1.jar (3.9 kB at 205 kB/s)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/shade-3.4.6-20170427.203559-1.jar
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/service-client-3.4.6-20170427.203558-1.jar (3.1 kB at 126 kB/s)
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/shade-3.4.6-20170427.203559-1.jar (2.2 kB at 67 kB/s)
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/webgui-3.4.6-20170427.203559-1.war (443 kB at 4.6 MB/s)
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/assembly-3.4.6-20170427.203600-1.tar.gz (2.7 MB at 14 MB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.142 s
[INFO] Finished at: 2017-04-27T22:43:05+02:00
[INFO] Final Memory: 45M/3926M
[INFO] ------------------------------------------------------------------------
```

The second try via Maven 3.3.9:

```
~/ws-git/javaee/x (master *)$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/maven
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

Furthermore the same call of Maven with the same result:

```
~/ws-git/javaee/x (master *)$ mvn org.apache.maven.plugins:maven-dependency-plugin:3.0.0:get -Dartifact=com.soebes.examples.j2ee:assembly:LATEST:tar.gz -DrepoUrl=http://localhost:8081/nexus/content/repositories/releases/ -Dmaven.repo.local=$HOME/.m2/repository
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.0.0:get (default-cli) @ standalone-pom ---
[INFO] Resolving com.soebes.examples.j2ee:assembly:tar.gz:LATEST with transitive dependencies
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/maven-metadata.xml (422 B at 4.6 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/maven-metadata.xml (958 B at 55.0 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/assembly-3.4.6-20170427.203600-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/assembly-3.4.6-20170427.203600-1.pom (2 KB at 118.2 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/parent/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/parent/3.4.6-SNAPSHOT/maven-metadata.xml (607 B at 32.9 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/parent/3.4.6-SNAPSHOT/parent-3.4.6-20170427.203558-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/parent/3.4.6-SNAPSHOT/parent-3.4.6-20170427.203558-1.pom (4 KB at 235.5 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/maven-metadata.xml (780 B at 34.6 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/webgui-3.4.6-20170427.203559-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/webgui-3.4.6-20170427.203559-1.pom (808 B at 52.6 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/maven-metadata.xml (781 B at 38.1 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/service-3.4.6-20170427.203559-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/service-3.4.6-20170427.203559-1.pom (2 KB at 88.4 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/maven-metadata.xml (788 B at 42.8 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/service-client-3.4.6-20170427.203558-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/service-client-3.4.6-20170427.203558-1.pom (647 B at 35.1 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/maven-metadata.xml (780 B at 47.6 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/domain-3.4.6-20170427.203558-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/domain-3.4.6-20170427.203558-1.pom (576 B at 33.1 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/maven-metadata.xml
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/maven-metadata.xml (2 KB at 91.9 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/shade-3.4.6-20170427.203559-1.pom
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/shade-3.4.6-20170427.203559-1.pom (3 KB at 119.6 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/assembly-3.4.6-20170427.203600-1.tar.gz
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/webgui-3.4.6-20170427.203559-1.war
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/service-3.4.6-20170427.203559-1.jar
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/service-client-3.4.6-20170427.203558-1.jar
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/domain-3.4.6-20170427.203558-1.jar
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service-client/3.4.6-SNAPSHOT/service-client-3.4.6-20170427.203558-1.jar (4 KB at 192.0 KB/sec)
Downloading: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/shade-3.4.6-20170427.203559-1.jar
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/service/3.4.6-SNAPSHOT/service-3.4.6-20170427.203559-1.jar (4 KB at 237.2 KB/sec)
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/domain/3.4.6-SNAPSHOT/domain-3.4.6-20170427.203558-1.jar (4 KB at 151.1 KB/sec)
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/shade/3.4.6-SNAPSHOT/shade-3.4.6-20170427.203559-1.jar (3 KB at 67.1 KB/sec)
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/webgui/3.4.6-SNAPSHOT/webgui-3.4.6-20170427.203559-1.war (434 KB at 6275.6 KB/sec)
Downloaded: http://localhost:8081/nexus/content/groups/public/com/soebes/examples/j2ee/assembly/3.4.6-SNAPSHOT/assembly-3.4.6-20170427.203600-1.tar.gz (2591 KB at 21234.8 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.098 s
[INFO] Finished at: 2017-04-27T22:44:41+02:00
[INFO] Final Memory: 43M/3926M
[INFO] ------------------------------------------------------------------------
```

Furthermore if you call without `repoUrl` it will work also based on the location in the `settings.xml` file which defines the locations to consume the artifacts from.
As I can see from the log output you are using a `pom.xml` from where you are calling it..I've also tested having a `pom.xml` where I call it...same result everything Ok. No exception...As I assume you are running this from a Jenkins server (based on the given references of `&#36;{WORKSPACE`). Do you use the Maven Job Type in Jenkins? If yes try to run the same without means in a freestyle job type...

**Comment by jira-importer** [comment]
**[Michael Dikman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=archmisha)** commented

I do create it via assembly-plugin and appendassemblyId:false
I am running from jenkins, but executing the command using execute shell. not in a maven type job.
I can also reproduce this from command line, not inside jenkins.
I don't have a pom. I just execute this command, similar to you.

My mvn -v:
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T19:39:06Z)
Maven home: /home/ubuntu/tools/hudson.tasks.Maven_MavenInstallation/maven_reportium_new
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.7.0_80/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-48-generic", arch: "amd64", family: "unix"

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Hi Michael,
first thanks for your detailed information. Two question: First can you run your failing command with `-X` option and redirect the output to a file and attach that log file here to the ticket (of course with sensitive information wiped out or you could send the logoutput to me privately) and second are you able to run a SNAPSHOT version of the plugin (maybe a the current trunk version) which can be could offered via https://repository.apache.org/content/repositories/snapshots/ ? Furthermore I can create a test version with more debugging output in it to find the location of the issue...

BTW: Can you please test the commands on your site  with downloaded version from the apache maven sites (maven.apache.org/download.cgi just download and untar the tar.gz and test the same commands) cause I see: {{Maven home: /home/ubuntu/tools/hudson.tasks.Maven_MavenInstallation/maven_reportium_new
}}  which is if I not mistaken an automatic download of Jenkins...?

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

[Michael Dikman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=archmisha) Do you have further details?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No further details provided.
