### ISSUE TITLE
[MDEP-274] unpack mojo suffers from PLXUTILS-64

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#1104]
**[Peter Lynch](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=plynch)** opened **[MDEP-274](https://issues.apache.org/jira/browse/MDEP-274?redirect=false)** and commented

Unpacking a tar.gz file with dependency:unpack I got this

```

org.codehaus.plexus.archiver.ArchiverException: chmod exit code was: 1
	at org.codehaus.plexus.archiver.util.ArchiveEntryUtils.chmod(ArchiveEntryUtils.java:59)
	at org.codehaus.plexus.archiver.zip.AbstractZipUnArchiver.extractFile(AbstractZipUnArchiver.java:236)
	at org.codehaus.plexus.archiver.tar.TarUnArchiver.execute(TarUnArchiver.java:92)

```

The problem stems from PLXUTILS-64. The dependency on plexus-utils should be upgraded to at least
version 1.5.1 to prevent this problem.

I tested with this as a plugin dependency and the problem went away.

\<dependency>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-utils\</artifactId>
\<version>1.5.15\</version>
\</dependency>

---

**Affects:** 2.1

**Issue Links:**
- [MDEP-138](https://issues.apache.org/jira/browse/MDEP-138) unpack of tar files fail with ArchiverException: chmod exit code was: 1
 (_**"duplicates"**_)

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

See MDEP-138
