### ISSUE TITLE
[MDEP-194] ArchiverException when using maven dependency plugin in multi-module projects

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#1179]
**[Sascha Schumann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sascha)** opened **[MDEP-194](https://issues.apache.org/jira/browse/MDEP-194?redirect=false)** and commented

Having the following module hierarchy the _unpack-dependencies_ goal of the _maven-dependency-plugin_ produces an _ArchiverException_.
* A
  * B
  * C (depends on B)

I took a quick look into the code and found that when unpacking the dependencies of module **C** the method _unpack(File, File, String, String)_ of class _org.apache.maven.plugin.dependency.AbstractDependencyMojo_ gets passed the **target/classes** directory of **B** as source file (instead of the created jar).

part of the pom.xml which caused the error:

```xml
<profile>
  <id>multi-module-coverage</id>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>unpack-dependencies</id>
            <phase>process-classes</phase>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/classes</outputDirectory>
              <excludeClassifiers>tests</excludeClassifiers>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</profile>
```

exception:

```
org.codehaus.plexus.archiver.ArchiverException: The source must not be a directory.
        at org.codehaus.plexus.archiver.AbstractUnArchiver.validate(AbstractUnArchiver.java:174)
        at org.codehaus.plexus.archiver.AbstractUnArchiver.extract(AbstractUnArchiver.java:107)
        at org.apache.maven.plugin.dependency.AbstractDependencyMojo.unpack(AbstractDependencyMojo.java:266)
        at org.apache.maven.plugin.dependency.UnpackDependenciesMojo.execute(UnpackDependenciesMojo.java:90)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

---

**Affects:** 2.0

**Attachments:**
- [maven-dependency-plugin-2.5-SNAPSHOT-copy-artifact.patch](https://issues.apache.org/jira/secure/attachment/12715010/maven-dependency-plugin-2.5-SNAPSHOT-copy-artifact.patch) (_4.29 kB_)
- [maven-dependency-plugin-2.5-SNAPSHOT-copy-artifact2.patch](https://issues.apache.org/jira/secure/attachment/12715190/maven-dependency-plugin-2.5-SNAPSHOT-copy-artifact2.patch) (_5.39 kB_)
- [mdep-194-its-aoc.diff](https://issues.apache.org/jira/secure/attachment/12715099/mdep-194-its-aoc.diff) (_13.79 kB_)
- [mdp-194-src-main-aoc.diff](https://issues.apache.org/jira/secure/attachment/12715193/mdp-194-src-main-aoc.diff) (_2.65 kB_)
- [plexus-archiver-1.0-alpha-9-DirectoryUnArchiver.diff](https://issues.apache.org/jira/secure/attachment/12715171/plexus-archiver-1.0-alpha-9-DirectoryUnArchiver.diff) (_6.77 kB_)

**Issue Links:**
- [MDEP-98](https://issues.apache.org/jira/browse/MDEP-98) dependency:unpack: The source must not be a directory
 (_**"duplicates"**_)
- [MDEP-354](https://issues.apache.org/jira/browse/MDEP-354) dependency:unpack-dependencies fail if artifact is à directory
 (_**"is duplicated by"**_)
- [MDEP-187](https://issues.apache.org/jira/browse/MDEP-187) dependency:copy fails when invoked from m2e with workspace resolution enabled, or more generally when copying within reactor for phases earlier than package

45 votes, 30 watchers

**Comment by jira-importer** [comment]
**[derek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dokeeffe)** commented

As a work around here is what we did.
In the project you want to unpack, add the maven assembly plugin to package a zip file of everything you need.

Then in the projects that needs this resource just specify zip as the archive instead of jar. (like below)
\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-dependency-plugin\</artifactId>
\<configuration>
\<artifactItems>
\<artifactItem>
\<groupId>com.derek.mega.application\</groupId>
\<artifactId>common-resources\</artifactId>
\<type>zip\</type>
\<overWrite>true\</overWrite>
\<outputDirectory>target/common-resources\</outputDirectory>
\<includes>**/*.properties,**/**.xml,**/**.sql,**/*.bat,**/*.sh\</includes>
\</artifactItem>
\</artifactItems>
\</configuration>
\<executions>
\<execution>
\<id>unpack-common-resources\</id>
\<goals>
\<goal>unpack\</goal>
\</goals>
\<phase>generate-resources\</phase>
\</execution>
\</executions>
\</plugin>

**Comment by jira-importer** [comment]
**[Thiago Leão Moreira](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tmoreira2020)** commented

This is the exactly problem that I have. Any intention to fix it? I'm using the version 2.1

**Comment by jira-importer** [comment]
**[Archimedes Trajano](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trajano)** commented

This is specifically for UNPACK goal

I think what could be done is to change the check so that if it detects that the source is a directory rather than an archive that it will just copy from the directory instead of trying to extract.

**Comment by jira-importer** [comment]
**[Michael Berg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mberg2007)** commented

I have experienced the same issue, but I would like to offer an alternative patch. I do not feel that the proper place to fix this problem is in the plexus unarchiver simply because that is where the exception manifests itself. The underlying issue is that the unpacker is being told to unpack a directory, which really does not make sense. Also, making such a change in the archiver could lead to regression issues elsewhere.

My patch is directed at the UnpackMojo itself, adding a check to see if the archive is really an archive or a directory, and in case of the latter, use the relevant plexus FileUtils method to copy the files over, rather than the archiver. It seems like a more logical choice to me.

This patch more or less implements the suggestion made by Archimedes Trajano above.

**Comment by jira-importer** [comment]
**[Michael Berg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mberg2007)** commented

See maven-dependency-plugin-2.5-SNAPSHOT-copy-artifact.patch

**Comment by jira-importer** [comment]
**[Art O Cathain](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=artbristol)** commented

I like your patch Michael, but I think it doesn't work if your artifactItem's \<includes> have a subdirectory e.g.
\<includes>xsd/*.xsd\</includes>

In this case the unpacker puts the xsd files in [outputdirectory]/xsd/, but the fileutils copy method (from your patch) puts them directly in [outputdirectory].

**Comment by jira-importer** [comment]
**[Michael Berg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mberg2007)** commented

Art, have you actually witnessed this? I have the following in my pom:

\<goals>
\<goal>unpack\</goal>
\</goals>
\<configuration>
	\<artifactItems>
		\<artifactItem>
			\<groupId>com.interform400.xml\</groupId>
			\<artifactId>plugin-web-base\</artifactId>
			\<version>${project.version}\</version>
			\<type>war\</type>
		\</artifactItem>
	\</artifactItems>
	\<includes>**/web.xml\</includes>
	\<outputDirectory>${project.build.directory}/plugin-web-base-unpack\</outputDirectory>
\</configuration>

When the build finishes, then inside the plugin-web-base-unpack folder I am seeing this:

plugin-web-base-unpack/
/WEB-INF/
/WEB-INF/web.xml

The WEB-INF folder was created automatically.

**Comment by jira-importer** [comment]
**[Art O Cathain](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=artbristol)** commented

Yeah, it's happening to me. I could try and make you a sample project? In your version, your \<includes> doesn't have any subdirectories directly defined in it, so I'd expect it to work.

Maybe as a workaround I could try the ** notation.

**Comment by jira-importer** [comment]
**[Art O Cathain](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=artbristol)** commented

Using ** makes no difference. I'm using type jar, you're using type war - could that be it?

**Comment by jira-importer** [comment]
**[Michael Berg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mberg2007)** commented

I would not think the dependency type mattered. The source directory should contain the already unpacked archive regardless of its type.

However, in my case I am building a war file rather than a jar file, perhaps that matters?

**Comment by jira-importer** [comment]
**[Art O Cathain](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=artbristol)** commented

It's happening to me with both war and jar types of project (in both cases the dependency is on a jar project)

**Comment by jira-importer** [comment]
**[Torsten Krah](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tkrah)** commented

CopyMojo does need the same patch like UnpackMojo.

**Comment by jira-importer** [comment]
**[Torsten Krah](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tkrah)** commented

Addition:

The problem with prefix annotation is still there, using something like "solr/**" does result in those directories not being created.

**Comment by jira-importer** [comment]
**[Michael Berg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mberg2007)** commented

Isn't it supposed to work that way? From a shell analogy, consider this:

$ cp /some/dir/* localdir/

I would not expect /some/dir to be created under localdir/ in this case.

Have you tried entering /solr/** / *

(remove the spaces, I have to enter them or the comment system thinks I'm trying to enter something in bold)

**Comment by jira-importer** [comment]
**[Torsten Krah](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tkrah)** commented

Thats correct, but i would want - i dont know how to do it yet - this one:

cp -R solr/ localdir/

I'll try the alternative.

**Comment by jira-importer** [comment]
**[Art O Cathain](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=artbristol)** commented

`@Michael` Either way seems reasonable to me, but the problem is that the files end up in a different directory depending on whether you do "mvn compile" (which didn't work at all before your patch) or "mvn install" (which did work). For compatibility I think it has to work the way it currently does in "mvn install".

**Comment by jira-importer** [comment]
**[Michael Berg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mberg2007)** commented

`@Art` Actually "mvn install" did not work either for me, before the patch. That's how I noticed the problem in the first place, our CI server began to fail for no apparent reason during an "mvn install" build.

I think "how it works" is the same regardless of which maven phase the unpack goal is bound to. It should be able to unpack files regardless.

**Comment by jira-importer** [comment]
**[Art O Cathain](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=artbristol)** commented

Thanks for your work on this Michael. Would it help if I created a small self-contained project that demonstrates the experience I've been having?

**Comment by jira-importer** [comment]
**[Gili](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cowwoc)** commented

Four years and counting. If you're not going to fix it anytime soon, please provide a workaround! What are we supposed to do?

**Comment by jira-importer** [comment]
**[Gili](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cowwoc)** commented

Grr. Note to self, this error also occurs if you attempt to unpack a dependency that requires a classifier but you omit it. Meaning, if you have:

* A
  * B (classifier = foo)
  * C (attempts to unpack B but without a classifier)

then C will throw an exception. If you add the classifier, however, it works.

**Comment by jira-importer** [comment]
**[Art O Cathain](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=artbristol)** commented

I have a new patch, based on Nicolas Cornaglia's patch C attached to MDEP-187.

**Comment by jira-importer** [comment]
**[Art O Cathain](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=artbristol)** commented

I have also created some integration tests

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

duplicate of MDEP-98: closing this duplicate will help focus everybody's energy
