### ISSUE TITLE
[MDEP-79] index out of bounds exception on analyze against maven-war-plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#608]
**[Brian E Fox](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf)** opened **[MDEP-79](https://issues.apache.org/jira/browse/MDEP-79?redirect=false)** and commented

[INFO] Compiling 2 source files to e:\svn\maven\maven-plugins\maven-war-plugin\t
arget\test-classes
[INFO] [dependency:analyze]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] 172
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.ArrayIndexOutOfBoundsException: 172
at org.objectweb.asm.ClassReader.\<init>(Unknown Source)
at org.objectweb.asm.ClassReader.\<init>(Unknown Source)
at org.objectweb.asm.ClassReader.\<init>(Unknown Source)
at org.apache.maven.shared.dependency.analyzer.asm.DependencyClassFileVi
sitor.visitClass(DependencyClassFileVisitor.java:60)
at org.apache.maven.shared.dependency.analyzer.ClassFileVisitorUtils.vis
itClass(ClassFileVisitorUtils.java:147)
at org.apache.maven.shared.dependency.analyzer.ClassFileVisitorUtils.acc
eptDirectory(ClassFileVisitorUtils.java:132)
at org.apache.maven.shared.dependency.analyzer.ClassFileVisitorUtils.acc
ept(ClassFileVisitorUtils.java:70)
at org.apache.maven.shared.dependency.analyzer.asm.ASMDependencyAnalyzer
.analyze(ASMDependencyAnalyzer.java:49)
at org.apache.maven.shared.dependency.analyzer.DefaultProjectDependencyA
nalyzer.buildDependencyClasses(DefaultProjectDependencyAnalyzer.java:141)
at org.apache.maven.shared.dependency.analyzer.DefaultProjectDependencyA
nalyzer.analyze(DefaultProjectDependencyAnalyzer.java:72)
at org.apache.maven.plugin.dependency.AnalyzeMojo.checkDependencies(Anal
yzeMojo.java:121)
at org.apache.maven.plugin.dependency.AnalyzeMojo.execute(AnalyzeMojo.ja
va:96)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:420)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandalone
Goal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:330)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:123)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0-alpha-4

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

I catch the exception and log the filename. These files in the war plugin are not valid class files, but ASM pukes on them instead of handling it gracefully.

[INFO] [dependency:analyze]
Unable to process: test-classes.unit.warexplodedmojo.test-dir.ExplodedWarWithSourceModificationCheck.WEB-INF.classes.sample-servlet
Unable to process: test-classes.unit.warexplodedmojo.test-dir.ExplodedWarWithSourceModificationCheck-test-data.classes.sample-servlet
Unable to process: test-classes.unit.warexplodedmojo.test-dir.ExplodedWar_WithClasses-test-data.classes.sample-servlet
Unable to process: test-classes.unit.warexplodedmojo.test-dir.ExplodedWar_WithResourceFiltering.WEB-INF.classes.sample-servlet
Unable to process: test-classes.unit.warexplodedmojo.test-dir.ExplodedWar_WithResourceFiltering-test-data.classes.sample-servlet
Unable to process: test-classes.unit.warexplodedmojo.test-dir.SimpleExplodedWar.WEB-INF.classes.sample-servlet
Unable to process: test-classes.unit.warexplodedmojo.test-dir.SimpleExplodedWar-test-data.classes.sample-servlet
