### ISSUE TITLE
[MDEP-98] dependency:unpack: The source must not be a directory

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#639]
**[Pablo Muñiz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pablo.muniz)** opened **[MDEP-98](https://issues.apache.org/jira/browse/MDEP-98?redirect=false)** and commented

Using maven-dependency-plugin in a multimodule project inside a module wich has a dependency with another module in the same project the next error ocurrs :

```
org.codehaus.plexus.archiver.ArchiverException: The source must not be a directory.
        at org.codehaus.plexus.archiver.AbstractUnArchiver.validate(AbstractUnArchiver.java:98)
        at org.codehaus.plexus.archiver.AbstractUnArchiver.extract(AbstractUnArchiver.java:84)
        at org.apache.maven.plugin.dependency.AbstractDependencyMojo.unpack(AbstractDependencyMojo.java:232)
        at org.apache.maven.plugin.dependency.UnpackDependenciesMojo.execute(UnpackDependenciesMojo.java:72)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error unpacking file: c:\D\desarrollo\proyectos\plataforma\platform-core\target\classes to: c:\D\desarrollo\proyectos\plataforma\platform-bundle\platform-bundle-jar\target\classes
org.codehaus.plexus.archiver.ArchiverException: The source must not be a directory.
```

Project structure is as follows:

plataforma
- platform-core
- platform-bundle
- platform-bundle-jar
- platform-bundle-src

and the error happens on executing any goal from parent pom. maven-dependency-plugin seems to receive a reference to target/classes directory for platform-core dependency instead of the URL to my local repository where platform-core is located.

---

**Affects:** 2.0-alpha-4

**Attachments:**
- [MDEP-98-ITs.patch](https://issues.apache.org/jira/secure/attachment/12715004/MDEP-98-ITs.patch) (_10.41 kB_)
- [mdep98-testcase-parent.zip](https://issues.apache.org/jira/secure/attachment/12715186/mdep98-testcase-parent.zip) (_14.90 kB_)
- [mdep98-testcase-parent-with-surefire.zip](https://issues.apache.org/jira/secure/attachment/12715146/mdep98-testcase-parent-with-surefire.zip) (_14.87 kB_)

**Issue Links:**
- [MDEP-194](https://issues.apache.org/jira/browse/MDEP-194) ArchiverException when using maven dependency plugin in multi-module projects
 (_**"is duplicated by"**_)
- [MDEP-354](https://issues.apache.org/jira/browse/MDEP-354) dependency:unpack-dependencies fail if artifact is à directory
 (_**"is duplicated by"**_)
- [MDEP-187](https://issues.apache.org/jira/browse/MDEP-187) dependency:copy fails when invoked from m2e with workspace resolution enabled, or more generally when copying within reactor for phases earlier than package

- [MDEP-259](https://issues.apache.org/jira/browse/MDEP-259) copy-dependencies fails with "Error copying artifact from .../target/classes to .../classes"

34 votes, 31 watchers

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

can you please attach a sample project to reproduce this?

**Comment by jira-importer** [comment]
**[Thiago Leão Moreira](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tmoreira2020)** commented

Is there any intention to fix this?

**Comment by jira-importer** [comment]
**[René Zanner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzanner)** commented

sure - that's logical. "i want the content of X in some folder." (i don't care whether X is an archive or a folder - just like windows displaying zip files as "compressed folders"). definitely better than to break the build...

**Comment by jira-importer** [comment]
**[Stevo Slavić](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sslavic)** commented

ITs prove that the maven-dependency-plugin works well, as designed. This is practically m2e issue.

By combining profiles and maven-resource-plugin:copy-resources I've managed to workaround this issue.

In a multi-module project there is a shared resources module (SRM). Other modules which reference SRM and need it's content unpacked have two profiles, non-m2e and m2e, former activated when m2e.version property is not defined and latter activated when m2e.version property is defined. In non-m2e profile maven-dependency-plugin:unpack-dependencies unpacks SRM, while in m2e profile maven-resources-plugin:copy-resources is configured to copy shared resources from SRM.

When build is run using maven on command line, m2e.version is not defined and maven-dependency-plugin will unpack SRM dependency from reactor. When build is run from eclipse using m2e, m2e.version is defined and m2e will copy resources.

Removing my vote.

**Comment by jira-importer** [comment]
**[Antonio Petrelli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apetrelli)** commented

It happens out of m2e too.
I have a multi-module project of this type:
parent
+-- jar (JNLP client)
+-- war (unpacks JNLP client)
+-- ear (pack web)

During "mvn site" call, the "unpack" goal breaks in the way shown above.
I will try to create a test case for this.

**Comment by jira-importer** [comment]
**[Antonio Petrelli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apetrelli)** commented

Sorry for the noise, it seems that the unpack was triggered in some ways by the Cobertura plugin. I thought that a workaround was to put the dependency to unpack as a provided dependency, however it does not work (I made some mistakes before).

**Comment by jira-importer** [comment]
**[Antonio Petrelli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apetrelli)** commented

Added test case to reproduce the problem. Cobertura plugin triggers the WAR build that fails to unpack a dependency.

**Comment by jira-importer** [comment]
**[Antonio Petrelli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apetrelli)** commented

Added testcase that uses Surefire report instead of Cobertura. So this seems not to be a Cobertura plugin related bug.
Probably, it's the way the build is triggered that make it fail.
However, the workaround is doing an "mvn package" before doing "mvn site". It seems that this way the WAR is not rebuilt and, therefore, the "unpack" goal is not called.

**Comment by jira-importer** [comment]
**[Antonio Petrelli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apetrelli)** commented

Stevo, just a comment about the last sentence about "mvn package" and "mvn site".
I don't think that unpack goal is run and it succeeds, but I think that the report executor notices that the build has been already done, and then it does not retry to build it. So it succeeds simply because the unpack does not run.

**Comment by jira-importer** [comment]
**[Art O Cathain](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=artbristol)** commented

There is some more activity on the duplicate MDEP-194. Can you try the patch there?

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

like MDEP-187, error message improved in [r1368261](http://svn.apache.org/viewvc?rev=1368261&view=rev)
this doesn't fix the problem but at least makes it easier to track
notice that another corner case to take care is when the dependency to unpack has a classifier/specific packaging: we can't imagine the content before the artifact has been packaged

**Comment by jira-importer** [comment]
**[James Davis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=davija)** commented

As far as the comment about needing to do an install on the modules, that is not always a desirable thing to do.  If you have multiple builds running on the same box with each of them installing, your build may end up getting the artifact published by the other build, not the one from this build.  The only way to ensure you have the right contents is to use the artifact from the same workspace.

As a side-note, I updated to the latest version (2.5) and used the package goal and all seems to be working.

**Comment by jira-importer** [comment]
**[Michal Rembiszewski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mrembisz)** commented

I had this issue also with sonar:sonar. There is a simple workaround which could be applicable for some other scenarios as well. The problem is unpack will attempt to use folder as its source only if package was not executed for this module as part of the build.

So in my case the workaround was to run "mvn package sonar:sonar" instead of "mvn sonar:sonar". The former does certain things twice so it's less effective, but when reactor detects package was performed, it will unpack dependencies from jar instead of going for the folder. Probably the workaround can be improved through explicit package execution.

**Comment by jira-importer** [comment]
**[Samuel Langlois](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slanglois)** commented

For Sonar, the "official" workaround is to use the sonar.phase parameter, asking Sonar to run the build up to a certain phase:

```
mvn sonar:sonar -Dsonar.phase=package
```

This is probably quite similar to the previous comment, and of course it runs the tests twice.

(I must confess I sometimes move the goal that packages from the `package` phase to the `process-test-classes` phase, so that I only have to build up to that phase, avoiding the `test` phase. Shame on me...)

**Comment by jira-importer** [comment]
**[Michael K](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ufkub)** commented

This still occurs in some projects.
Workaround:
- First execute "mvn -DskipTests=true package".
- After that, "mvn site" succeeds.
