### ISSUE TITLE
[MDEP-142] Path with space makes the dependency:unpack goal fail

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#649]
**[Pierre-Arnaud Marcelot](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pamarcelot)** opened **[MDEP-142](https://issues.apache.org/jira/browse/MDEP-142?redirect=false)** and commented

Configuration in pom.xml file:
\<build>
\<plugins>
\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-dependency-plugin\</artifactId>
\<executions>
\<execution>
\<id>launcher-macosx (unpack)\</id>

\

\<phase>generate-resources\</phase>
\<goals>
\<goal>unpack\</goal>
\</goals>
\<configuration>
\<overWrite>true\</overWrite>
\<markersDirectory>${project.build.directory}/dependency-maven-plugin-markers/macosx\</markersDirectory>
\<artifactItems>
\<artifactItem>
\<groupId>org.apache.directory.studio\</groupId>
\<artifactId>launcher-macosx\</artifactId>
\<type>tar.gz\</type>
\<outputDirectory>${studio-dir}-macosx\</outputDirectory>
\</artifactItem>
\<artifactItem>
\<groupId>org.eclipse.equinox.launcher.carbon\</groupId>
\<artifactId>macosx\</artifactId>
\<type>tar.gz\</type>
\<outputDirectory>${studio-dir}-macosx/Apache Directory Studio.app/Contents/Resources/Java/plugins\</outputDirectory>
\</artifactItem>
\</artifactItems>
\</configuration>
\</execution>
\</executions>
\</plugin>
\</plugins>
\</build>

Maven output:
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Directory Studio Build
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean]
[INFO] Deleting directory /Users/pajbam/Development/Apache/studio-maven/studio/target
[INFO] Deleting directory /Users/pajbam/Development/Apache/studio-maven/studio/target/classes
[INFO] Deleting directory /Users/pajbam/Development/Apache/studio-maven/studio/target/test-classes
[INFO] Deleting directory /Users/pajbam/Development/Apache/studio-maven/studio/target/site
[INFO] [remote-resources:process {execution: default}]
[INFO] [dependency:unpack {execution: launcher-macosx (unpack)}]
[INFO] Configured Artifact: org.apache.directory.studio:launcher-macosx:?:tar.gz
[INFO] Configured Artifact: org.eclipse.equinox.launcher.carbon:macosx:?:tar.gz
[INFO] Unpacking /Users/pajbam/.m2/repository/org/apache/directory/studio/launcher-macosx/1.1.0/launcher-macosx-1.1.0.tar.gzto
/Users/pajbam/Development/Apache/studio-maven/studio/target/ApacheDirectoryStudio-macosx
with Includes null and excludes:null
[INFO] Expanding /Users/pajbam/.m2/repository/org/apache/directory/studio/launcher-macosx/1.1.0/launcher-macosx-1.1.0.tar.gz to /tmp/tmp6522.tar
[INFO] Expanding: /tmp/tmp6522.tar into /Users/pajbam/Development/Apache/studio-maven/studio/target/ApacheDirectoryStudio-macosx
[WARNING] -------------------------------
[WARNING] Standard error:
[WARNING] -------------------------------
[WARNING]
[WARNING] -------------------------------
[WARNING] Standard output:
[WARNING] -------------------------------
[WARNING] /bin/sh: line 0: cd: /Users/pajbam/Development/Apache/studio-maven/studio/target/ApacheDirectoryStudio-macosx/Apache: No such file or directory

[WARNING] -------------------------------
org.codehaus.plexus.archiver.ArchiverException: chmod exit code was: 1
at org.codehaus.plexus.archiver.util.ArchiveEntryUtils.chmod(ArchiveEntryUtils.java:59)
at org.codehaus.plexus.archiver.zip.AbstractZipUnArchiver.extractFile(AbstractZipUnArchiver.java:236)
at org.codehaus.plexus.archiver.tar.TarUnArchiver.execute(TarUnArchiver.java:92)
at org.codehaus.plexus.archiver.tar.TarGZipUnArchiver.execute(TarGZipUnArchiver.java:76)
at org.codehaus.plexus.archiver.AbstractUnArchiver.extract(AbstractUnArchiver.java:108)
at org.apache.maven.plugin.dependency.AbstractDependencyMojo.unpack(AbstractDependencyMojo.java:266)
at org.apache.maven.plugin.dependency.fromConfiguration.UnpackMojo.unpackArtifact(UnpackMojo.java:122)
at org.apache.maven.plugin.dependency.fromConfiguration.UnpackMojo.execute(UnpackMojo.java:95)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error unpacking file: /Users/pajbam/.m2/repository/org/apache/directory/studio/launcher-macosx/1.1.0/launcher-macosx-1.1.0.tar.gz to: /Users/pajbam/Development/Apache/studio-maven/studio/target/ApacheDirectoryStudio-macosx
org.codehaus.plexus.archiver.ArchiverException: chmod exit code was: 1

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 minutes 31 seconds
[INFO] Finished at: Tue Feb 05 11:50:34 CET 2008
[INFO] Final Memory: 35M/63M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0-alpha-4, 2.0

**Attachments:**
- [AbstractDependencyPluginITCase.java](https://issues.apache.org/jira/secure/attachment/12715066/AbstractDependencyPluginITCase.java) (_10.48 kB_)
- [DuplicateFilesTest.java](https://issues.apache.org/jira/secure/attachment/12714993/DuplicateFilesTest.java) (_4.53 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12715126/pom.xml) (_8.29 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12715170/pom.xml) (_2.00 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12715123/pom.xml) (_1.27 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12715060/pom.xml) (_5.94 kB_)

**Issue Links:**
- [MDEP-138](https://issues.apache.org/jira/browse/MDEP-138) unpack of tar files fail with ArchiverException: chmod exit code was: 1
 (_**"duplicates"**_)

2 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Chris Ryan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lazjen)** commented

I also get this problem with:

Linux (2.6.28-gentoo-r1)
java version "1.6.0_07" and  "1.6.0_13"
Maven 2.0.10

and maven-dependency-plugin 2.0+, including 2.0, 2.0-alpha-4, 2.1

I have a workaround that fixes the problem.  It's far from ideal, however it may give someone the necessary info to solve this issue correctly.

Here's what I did:

I got checkouts of the source (see below) and made a number of changes, mostly version changes.  I built everything, sometimes with -DskipTests to get a successful build (maven-dependency-plugin and part of the plexus-components failed for me).  This produced a maven-dependency-plugin of 2.2-SNAPSHOT which I then used in my main project with success.

Checkouts:
plexus-utils: http://svn.codehaus.org/plexus/plexus-utils/trunk  (rev 8158)
plexus-classworlds:  http://svn.codehaus.org/plexus/plexus-classworlds/trunk  (rev 8158)
plexus-components: http://svn.codehaus.org/plexus/plexus-components/trunk (rev 8158)
plexus-containers:  http://svn.codehaus.org/plexus/plexus-containers/trunk (rev 8158)
maven-dependency-plugin:  https://svn.apache.org/repos/asf/maven/plugins/trunk/maven-dependency-plugin (rev 769222)

I made the following changes (I'll attach the modified files later):

***************

plexus-utils:

svn diff pom.xml
Index: pom.xml

---

--- pom.xml	(revision 8158)
+++ pom.xml	(working copy)
@@ -47,7 +47,7 @@
\<dependency>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-interpolation\</artifactId>
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    <version>1.3</version>

+ 

      <version>1.9-SNAPSHOT</version>

  \</dependency>
  \</dependencies>

***************

***************

plexus-classworlds: no changes, built version 1.5-SNAPSHOT

***************

***************

plexus-components:

svn st -u
M             8158   plexus-archiver/src/test/java/org/codehaus/plexus/archiver/DuplicateFilesTest.java
M             8158   plexus-archiver/pom.xml

svn diff plexus-archiver/src/test/java/org/codehaus/plexus/archiver/DuplicateFilesTest.java
Index: plexus-archiver/src/test/java/org/codehaus/plexus/archiver/DuplicateFilesTest.java

---

--- plexus-archiver/src/test/java/org/codehaus/plexus/archiver/DuplicateFilesTest.java	(revision 8158)
+++ plexus-archiver/src/test/java/org/codehaus/plexus/archiver/DuplicateFilesTest.java	(working copy)
@@ -1,20 +1,20 @@
package org.codehaus.plexus.archiver;

+import java.io.BufferedInputStream;
+import java.io.BufferedReader;
+import java.io.File;
+import java.io.FileInputStream;
+import java.io.FileReader;
+import java.util.Enumeration;
+
+import org.codehaus.plexus.MutablePlexusContainer;
import org.codehaus.plexus.PlexusTestCase;
-import org.codehaus.plexus.archiver.zip.AbstractZipArchiver;
+import org.codehaus.plexus.archiver.tar.TarInputStream;
+import org.codehaus.plexus.archiver.zip.ZipEntry;
import org.codehaus.plexus.archiver.zip.ZipFile;
-import org.codehaus.plexus.archiver.zip.ZipEntry;
-import org.codehaus.plexus.archiver.tar.TarInputStream;
import org.codehaus.plexus.logging.Logger;
import org.codehaus.plexus.util.FileUtils;

-import java.io.File;
-import java.io.FileReader;
-import java.io.BufferedReader;
-import java.io.BufferedInputStream;
-import java.io.FileInputStream;
-import java.util.Enumeration;

---

/**
* `@author` Erik Engstrom
  */
  @@ -31,7 +31,7 @@
  throws Exception
  {
  super.setUp();

- 

      getContainer().getLoggerManager().setThreshold( Logger.LEVEL_DEBUG );

+ 

      ((MutablePlexusContainer)getContainer()).getLoggerManager().setThreshold( Logger.LEVEL_DEBUG );

  }

  public void testZipArchiver()

svn diff plexus-archiver/pom.xml
Index: plexus-archiver/pom.xml

---

--- plexus-archiver/pom.xml	(revision 8158)
+++ plexus-archiver/pom.xml	(working copy)
@@ -27,10 +27,12 @@
\<dependency>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-container-default\</artifactId>
+

    <version>1.1-SNAPSHOT</version>

\</dependency>
\<dependency>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-utils\</artifactId>
+ 

      <version>1.5.9-SNAPSHOT</version>

  \</dependency>
  \<dependency>
  \<groupId>org.codehaus.plexus\</groupId>

***************

***************

plexus-containers:

svn diff plexus-container-default/pom.xml
Index: plexus-container-default/pom.xml

---

--- plexus-container-default/pom.xml	(revision 8158)
+++ plexus-container-default/pom.xml	(working copy)
@@ -10,23 +10,45 @@
\<artifactId>plexus-container-default\</artifactId>

\<name>Plexus :: Default Container\</name>
+
+

\<repositories>
+ 

\<repository>
+ 

      <releases>

+ 

      <enabled>true</enabled>

+ 

      <updatePolicy>always</updatePolicy>

+ 

      <checksumPolicy>warn</checksumPolicy>

+ 

      </releases>

+ 

      <snapshots>

+ 

      <enabled>true</enabled>

+ 

      <updatePolicy>always</updatePolicy>

+ 

      <checksumPolicy>warn</checksumPolicy>

+ 

      </snapshots>

+ 

      <id>codehausSnapshots</id>

+ 

      <name>OW2</name>

+ 

      <url>http://maven.ow2.org/maven2-snapshot/</url>

+ 

      <layout>default</layout>

+ 

\</repository>
+ 

\</repositories>
\<dependencies>
\<dependency>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-utils\</artifactId>
+ 

      <version>1.5.9-SNAPSHOT</version>

  \</dependency>
  \<dependency>
  \<groupId>org.codehaus.plexus\</groupId>
  \<artifactId>plexus-classworlds\</artifactId>
+ 

      <version>1.5-SNAPSHOT</version>

  \</dependency>
  \<dependency>
  \<groupId>org.apache.xbean\</groupId>
  \<artifactId>xbean-reflect\</artifactId>
  \</dependency>
  \<dependency>

- 

      <groupId>com.google.code.google-collections</groupId>

+ 

      <groupId>com.google.common</groupId>
      <artifactId>google-collect</artifactId>

+ 

      <version>0.5-SNAPSHOT</version>

  \</dependency>
  \</dependencies>

***************

***************

maven-dependency-plugin:

svn st -u
M           769222   src/test/java/org/apache/maven/plugin/dependency/its/AbstractDependencyPluginITCase.java
M           769222   pom.xml
Status against revision: 769224

svn diff src/test/java/org/apache/maven/plugin/dependency/its/AbstractDependencyPluginITCase.java
Index: src/test/java/org/apache/maven/plugin/dependency/its/AbstractDependencyPluginITCase.java

---

--- src/test/java/org/apache/maven/plugin/dependency/its/AbstractDependencyPluginITCase.java	(revision 769222)
+++ src/test/java/org/apache/maven/plugin/dependency/its/AbstractDependencyPluginITCase.java	(working copy)
@@ -32,9 +32,9 @@
import org.apache.maven.shared.test.plugin.PluginTestTool;
import org.apache.maven.shared.test.plugin.ProjectTool;
import org.apache.maven.shared.test.plugin.TestToolsException;
-import org.codehaus.classworlds.ClassRealm;
import org.codehaus.plexus.PlexusContainer;
import org.codehaus.plexus.PlexusTestCase;
+import org.codehaus.plexus.classworlds.realm.ClassRealm;
import org.codehaus.plexus.util.StringUtils;

/**

svn diff pom.xml
Index: pom.xml

---

--- pom.xml	(revision 769222)
+++ pom.xml	(working copy)
@@ -82,7 +82,7 @@
\</issueManagement>

\<properties>
-    \<maven.version>2.0.9\</maven.version>
+    \<maven.version>2.0.10\</maven.version>
\</properties>
\<dependencies>
@@ -126,7 +126,7 @@
\<dependency>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-archiver\</artifactId>
-      \<version>1.0-alpha-9\</version>
+      \<version>1.0-alpha-12-SNAPSHOT\</version>
\<exclusions>
\<exclusion>
\<groupId>org.codehaus.plexus\</groupId>
@@ -141,7 +141,7 @@
\<dependency>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-utils\</artifactId>
-      \<version>1.4.6\</version>
+      \<version>1.5.9-SNAPSHOT\</version>
\</dependency>
\<dependency>
\<groupId>org.apache.maven.shared\</groupId>
@@ -157,7 +157,7 @@
\<dependency>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-container-default\</artifactId>
-      \<version>1.0-alpha-9-stable-1\</version>
+      \<version>1.1-SNAPSHOT\</version>
\</dependency>
\<dependency>
\<groupId>org.apache.maven.shared\</groupId>
@@ -177,7 +177,7 @@
\<dependency>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-io\</artifactId>
-      \<version>1.0-alpha-1\</version>
+      \<version>1.0-alpha-4-SNAPSHOT\</version>
\<exclusions>
\<exclusion>
\<groupId>org.codehaus.plexus\</groupId>
***************

**Comment by jira-importer** [comment]
**[Chris Ryan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lazjen)** commented

plexus-archiver/pom.xml

**Comment by jira-importer** [comment]
**[Chris Ryan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lazjen)** commented

plexus-archiver/src/test/java/org/codehaus/plexus/archiver/DuplicateFilesTest.java

**Comment by jira-importer** [comment]
**[Chris Ryan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lazjen)** commented

plexus-containers/plexus-container-default/pom.xml

**Comment by jira-importer** [comment]
**[Chris Ryan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lazjen)** commented

maven-dependency-plugin/pom.xml

**Comment by jira-importer** [comment]
**[Chris Ryan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lazjen)** commented

maven-dependency-plugin/src/test/java/org/apache/maven/plugin/dependency/its/AbstractDependencyPluginITCase.java

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

add IT test case, can't seem to reproduce the issue at rev 894544. Am i missing any thing?

Revision: 894544
Author: dantran
Date: 9:10:23 PM, Tuesday, December 29, 2009
Message:
MDEP-142: add IT, not able to reproduce the issue.

---

Added : /maven/plugins/trunk/maven-dependency-plugin/src/it/unpack
Added : /maven/plugins/trunk/maven-dependency-plugin/src/it/unpack/invoker.properties
Added : /maven/plugins/trunk/maven-dependency-plugin/src/it/unpack/pom.xml
Added : /maven/plugins/trunk/maven-dependency-plugin/src/it/unpack/validate.bsh
