### ISSUE TITLE
[MDEP-121] UnsupportedOperationException on depdendency:analyze

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#672]
**[William Ferguson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=william_ferguson_au@yahoo.com)** opened **[MDEP-121](https://issues.apache.org/jira/browse/MDEP-121?redirect=false)** and commented

Executing:

```
mvn org.apache.maven.plugins:maven-dependency-plugin:2.0-alpha-5-SNAPSHOT:analyze
```

on 3-DEC-2007 (ie 2.0-alpha-5-20070703.005757) produced:

```
[INFO] snapshot org.codehaus.plexus:plexus-archiver:1.0-alpha-9-SNAPSHOT: checking for updates from snapshot
[INFO] snapshot org.apache.maven.shared:maven-dependency-analyzer:1.0-alpha-3-SNAPSHOT: checking for updates from snapshot
[INFO] [dependency:analyze]
[INFO] Used undeclared dependencies:
[WARNING]    commons-logging:commons-logging:jar:1.0:compile
[INFO] Unused declared dependencies:
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableCollection$1.remove(Collections.java:1012)
        at org.apache.maven.plugin.dependency.AnalyzeMojo.checkDependencies(AnalyzeMojo.java:213)
        at org.apache.maven.plugin.dependency.AnalyzeMojo.execute(AnalyzeMojo.java:162)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 58 seconds
[INFO] Finished at: Mon Dec 03 12:33:25 EST 2007
[INFO] Final Memory: 14M/28M
[INFO] ------------------------------------------------------------------------
```

NB I was using the snapshot because I had just run dependency:tree

Executing

```
mvn org.apache.maven.plugins:maven-dependency-plugin:2.0-alpha-4:analyze
```

does not cause the UnsupportedOperationException to occur.

But the error doesn't occur in the trunk, so maybe time to release a new snapshot or even a new release?

---

**Affects:** 2.0

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

New snapshot deployed. Release is coming soon, we needed 2.0.8 to be out first.
