### ISSUE TITLE
[MDEP-301] Allow build-classpath to output to property

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#744]
**[Bjorn Beskow](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=beskow)** opened **[MDEP-301](https://issues.apache.org/jira/browse/MDEP-301?redirect=false)** and commented

I frequently have the need to set the bootClasspath for the compiler plugin, and would like to do it from project dependencies. Hence I would like to be able to get the output of build-classpath to a property instead of a file.

Attached is a patch which adds an "outputProperty" property, and assigns the classpath value to it if specified.

---

**Affects:** 2.1

**Attachments:**
- [build-path-to-property.patch](https://issues.apache.org/jira/secure/attachment/12715001/build-path-to-property.patch) (_3.33 kB_)
- [mdep-301.diff](https://issues.apache.org/jira/secure/attachment/12715203/mdep-301.diff) (_3.70 kB_)
- [mdep-301.diff](https://issues.apache.org/jira/secure/attachment/12715015/mdep-301.diff) (_3.62 kB_)

3 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Baron Roberts](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baron1405)** commented

This would be a very useful feature. Currently, the only way to obtain the path for use within the POM requires using the antrun plugin. That adds needless overhead and clustters the POM with pieces of Ant.

**Comment by jira-importer** [comment]
**[Ryan Heinen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rheinen)** commented

Updated patch which applies cleanly against trunk and 2.6 and uses `@Property` annotation for consistency with the rest of the mojo.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

The patch cause build failure.

```
testEnvironment(org.apache.maven.plugin.dependency.TestBuildClasspathMojo)  Time elapsed: 0.075 sec  <<< FAILURE!
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertNotNull(Assert.java:217)
	at junit.framework.Assert.assertNotNull(Assert.java:210)
	at org.apache.maven.plugin.dependency.TestBuildClasspathMojo.testEnvironment(TestBuildClasspathMojo.java:89)
```

**Comment by jira-importer** [comment]
**[Ryan Heinen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rheinen)** commented

Sorry for breaking the test. I've updated the patch so that the tests now pass.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

applied http://svn.apache.org/r1442131
Thanks for the patch !
