### ISSUE TITLE
[MDEP-366] NPE when running site

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#811]
**[Paul Nyheim](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pnyheim)** opened **[MDEP-366](https://issues.apache.org/jira/browse/MDEP-366?redirect=false)** and commented

I have configured the `analyze-report` report in my reporting section of pom.xml

```xml
<reporting>
  <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.5</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>analyze-report</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
  </plugins>
</reporting>
```

And when I try to run `mvn site`, I get this NPE:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.1:site (default-site) on project : Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.1:site failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.1:site (default-site) on project : Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.1:site failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.1:site failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.plugin.dependency.AnalyzeReportMojo.executeReport(AnalyzeReportMojo.java:100)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:135)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:228)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more

```

---

**Affects:** 2.5

**Attachments:**
- [mdep-366.patch](https://issues.apache.org/jira/secure/attachment/12715107/mdep-366.patch) (_1.78 kB_)
- [mdep-366-it.patch](https://issues.apache.org/jira/secure/attachment/12715199/mdep-366-it.patch) (_776 bytes_)

**Issue Links:**
- [MDEP-388](https://issues.apache.org/jira/browse/MDEP-388) NPE in analyze-report
 (_**"is duplicated by"**_)

7 votes, 9 watchers

**Comment by jira-importer** [comment]
**[Jason Chaffee](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jchaffee)** commented

Seeing the same error. Using maven 3.0.x.

**Comment by jira-importer** [comment]
**[Brent Pacheco](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brent.pacheco)** commented

I am also seeing this same error, using maven 3.0.4.   I do not see the issue with version 2.4.

**Comment by jira-importer** [comment]
**[Peter Janes](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=peterj)** commented

Here's an IT that triggers the bug (for some reason the project variable is null in AnalyzeReportMojo.java).

**Comment by jira-importer** [comment]
**[Peter Janes](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=peterj)** commented

Looks like the project variable was set as a Parameter in AnalyzeReportMojo.java instead of a Component (as in the others) when the plugin was migrated to annotations.  This should fix it, and updates the IT with a basic verify script.

**Comment by jira-importer** [comment]
**[Arnaud Heritier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aheritier)** commented

Thx a lot for this patch
Wil be solved in the next release
