### ISSUE TITLE
[MDEP-448] NullPointerException when classifier sources was chosen

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#888]
**[Reguel Wermelinger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lordeagle)** opened **[MDEP-448](https://issues.apache.org/jira/browse/MDEP-448?redirect=false)** and commented

The execution of the copy-dependencies goal fails if the classifier "sources" is selected the mojo fails with a NullPointerException.

Somehow i can work around the bug by removing the classifier afterwards: \<stripClassifier>true\</stripClassifier>.
But then the \<overwriteIfNewer> flag is ignored. which results in lot's of unwanted file copy changes during my builds.

```xml
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy-dependencies (thirdparty) on project ch.ivyteam.testarea.depency: Execution thirdparty of goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy-dependencies failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy-dependencies (thirdparty) on project ch.ivyteam.testarea.depency: Execution thirdparty of goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy-dependencies failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution thirdparty of goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy-dependencies failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.plugin.dependency.fromDependencies.CopyDependenciesMojo.doExecute(CopyDependenciesMojo.java:156)
	at org.apache.maven.plugin.dependency.AbstractDependencyMojo.execute(AbstractDependencyMojo.java:167)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
```

---

**Affects:** 2.8

**Attachments:**
- [copy-dependcy-npe-sample.zip](https://issues.apache.org/jira/secure/attachment/12715033/copy-dependcy-npe-sample.zip) (_55.54 kB_)

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

I have taken [your example](https://github.com/khmarbaise/mdep/tree/master/mdep-448) and can reproduce your problem. I have made a fix for this problem in [r1622859](http://svn.apache.org/r1622859).
Is it possible that you can check via a 2.9-SNAPSHOT of the maven-dependency-plugin. I have provided a SNAPSHOT version containing the fix. It would be nice if you can give feedback if successful or not.
