### ISSUE TITLE
[MDEP-445] dependency plugin fails with >9 threads

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#889]
**[Anthony Clark](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=anthonyclarka2)** opened **[MDEP-445](https://issues.apache.org/jira/browse/MDEP-445?redirect=false)** and commented

I'm running into an error when I try to use more than 9 threads on a 24 core server:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:analyze-report (analyze-report)
 on project enterprise-provided: An error has occurred in Dependency Analysis report generation. Could not find the
 template 'org/apache/maven/doxia/siterenderer/resources/default-site.vm -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-depen
dency-plugin:2.8:analyze-report (analyze-report) on project enterprise-provided: An error has occurred in Dependenc
y Analysis report generation.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuild
er.java:188)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuild
er.java:184)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in Dependency Analysis report gene
ration.
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:106)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 11 more
Caused by: org.apache.maven.doxia.siterenderer.RendererException: Could not find the template 'org/apache/maven/doxia/siterenderer/resources/default-site.vm
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.processTemplate(DefaultSiteRenderer.java:537)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.writeTemplate(DefaultSiteRenderer.java:508)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.generateDocument(DefaultSiteRenderer.java:485)
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:97)
        ... 13 more
[INFO] No sources to compile
```

I've corresponded with Kristian Rosenvold on the maven-users email list and he has written the following patch:

http://svn.apache.org/viewvc/maven/plugins/trunk/maven-dependency-plugin/pom.xml?r1=1591759&r2=1591758&pathrev=1591759

Please let me know if you need more details or a link to the mailing list thread in question/

---
No further details from [MDEP-445](https://issues.apache.org/jira/browse/MDEP-445?redirect=false)

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Thanks for the report !

Fixed in r1591759
