### ISSUE TITLE
[MDEP-469] analyze-report java.io.FileNotFoundException:

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#910]
**[jieryn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jieryn)** opened **[MDEP-469](https://issues.apache.org/jira/browse/MDEP-469?redirect=false)** and commented

Apache Maven 3.2.3, multi-module project, maven-dependency-plugin:analyze-report:2.9 throws FileNotFoundException during site phase (same exact project and configuration but with 2.8 is successful):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project dao: Error generating maven-dependency-plugin:2.9:analyze-report: Cannot analyze dependencies: /var/lib/jenkins/jobs/site_com.acme.proj/workspace/domain/target/classes (Is a directory) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project dao: Error generating maven-dependency-plugin:2.9:analyze-report: Cannot analyze dependencies
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating maven-dependency-plugin:2.9:analyze-report: Cannot analyze dependencies
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:146)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.maven.doxia.siterenderer.RendererException: Error generating maven-dependency-plugin:2.9:analyze-report: Cannot analyze dependencies
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:239)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:311)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:129)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:182)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:141)
	... 21 more
Caused by: org.apache.maven.reporting.MavenReportException: Cannot analyze dependencies
	at org.apache.maven.plugin.dependency.analyze.AnalyzeReportMojo.executeReport(AnalyzeReportMojo.java:145)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:196)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:224)
	... 25 more
Caused by: org.apache.maven.shared.dependency.analyzer.ProjectDependencyAnalyzerException: Cannot analyze dependencies
	at org.apache.maven.shared.dependency.analyzer.DefaultProjectDependencyAnalyzer.analyze(DefaultProjectDependencyAnalyzer.java:94)
	at org.apache.maven.plugin.dependency.analyze.AnalyzeReportMojo.executeReport(AnalyzeReportMojo.java:136)
	... 27 more
Caused by: java.io.FileNotFoundException: /var/lib/jenkins/jobs/site_com.acme.proj/workspace/domain/target/classes (Is a directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.jar.JarFile.<init>(JarFile.java:154)
	at java.util.jar.JarFile.<init>(JarFile.java:118)
	at org.apache.maven.shared.dependency.analyzer.DefaultProjectDependencyAnalyzer.buildArtifactClassMap(DefaultProjectDependencyAnalyzer.java:150)
	at org.apache.maven.shared.dependency.analyzer.DefaultProjectDependencyAnalyzer.analyze(DefaultProjectDependencyAnalyzer.java:72)
	... 28 more
```

---

**Affects:** 2.9

5 votes, 5 watchers

**Comment by jira-importer** [comment]
**[David Phillips](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=electrum)** commented

We see this error all the time, but for the analyze-only goal which we run in the process-test-classes phase.

**Comment by jira-importer** [comment]
**[Stephan Schroevers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stephan202)** commented

I can confirm that version 2.8 is not affected. Specific reproduction case:
1. Have an aggregator build with two modules _A_ and _B_.
2. Make sure _B_ depends on _A_.
3. Configure the `analyze-only` goal to be run during the `process-test-classes` phase.
4. Run ``mvn test`` on the aggragator (i.e., the top level module).

**Comment by jira-importer** [comment]
**[Stephan Schroevers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stephan202)** commented

Just upgraded to version 2.10, and I can no longer reproduce the issue. So I suspect this ticket can be closed as _Fixed_.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Cool thanks for the feedback.
So i will close the issue.
If you discover something different than don't hesitate to reopen ticket.
