### ISSUE TITLE
[MDEP-484] NullPointerException when using tree goal with include parameter

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-dependency-plugin#924]
**[Marvin Lütgenau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=l%C3%BCtti)** opened **[MDEP-484](https://issues.apache.org/jira/browse/MDEP-484?redirect=false)** and commented

The tree goal aborts with a NullPointerException when using the includes parameter, if there is any dependency to an artifact that uses a range version.

Example call:
mvn dependency:tree -Dverbose -Dincludes=:::*-SNAPSHOT

---

**Affects:** 2.10

**Attachments:**
- [dependency-issues.zip](https://issues.apache.org/jira/secure/attachment/12731908/dependency-issues.zip) (_2.51 kB_)
- [mdep484-m2.log](https://issues.apache.org/jira/secure/attachment/12730127/mdep484-m2.log) (_122.46 kB_)
- [mdep484-m3.log](https://issues.apache.org/jira/secure/attachment/12730128/mdep484-m3.log) (_30.75 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12731909/pom.xml) (_738 bytes_)

1 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Marvin Lütgenau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=l%C3%BCtti)** commented

Example pom.xml attached

**Comment by jira-importer** [comment]
**[Marvin Lütgenau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=l%C3%BCtti)** commented

Stacktrace:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:tree (default-cli) on project tree-npe: Execution default-cli of goal org.apache.maven.plugins:maven-dependency-plug
in:2.8:tree failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:tree (default-cli) on project tree-npe: Execution default-cli of goa
l org.apache.maven.plugins:maven-dependency-plugin:2.8:tree failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-dependency-plugin:2.8:tree failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at org.apache.maven.shared.artifact.filter.AbstractStrictPatternArtifactFilter.matches(AbstractStrictPatternArtifactFilter.java:168)
        at org.apache.maven.shared.artifact.filter.AbstractStrictPatternArtifactFilter.include(AbstractStrictPatternArtifactFilter.java:132)
        at org.apache.maven.shared.artifact.filter.AbstractStrictPatternArtifactFilter.include(AbstractStrictPatternArtifactFilter.java:96)
        at org.apache.maven.shared.dependency.tree.filter.ArtifactDependencyNodeFilter.accept(ArtifactDependencyNodeFilter.java:65)
        at org.apache.maven.shared.dependency.tree.filter.AndDependencyNodeFilter.accept(AndDependencyNodeFilter.java:80)
        at org.apache.maven.shared.dependency.tree.traversal.FilteringDependencyNodeVisitor.visit(FilteringDependencyNodeVisitor.java:73)
        at org.apache.maven.shared.dependency.tree.DependencyNode.accept(DependencyNode.java:306)
        at org.apache.maven.shared.dependency.tree.DependencyNode.accept(DependencyNode.java:310)
        at org.apache.maven.shared.dependency.tree.DependencyNode.accept(DependencyNode.java:310)
        at org.apache.maven.plugin.dependency.tree.TreeMojo.serializeVerboseDependencyTree(TreeMojo.java:402)
        at org.apache.maven.plugin.dependency.tree.TreeMojo.execute(TreeMojo.java:246)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
        ... 20 more
```

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Can you please check this with version 2.10 ? On which operation system did you tested this? Have you been aware of quoting ?

**Comment by jira-importer** [comment]
**[Christian Koppen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ck1)** commented

I can reproduce the problem using plugin version 2.10 under Maven 2 and Maven 3. Details about the environment can be found in the attached logs. Using quotes for the parameter `-Dincludes=:::*-SNAPSHOT` doesn't make a difference on Windows 7 x64.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

It looks like there is a problem on the file system:

I have found in the log files the following:

```
..
[DEBUG] Error releasing shared lock for resolution tracking file: C:\Users\user\.m2\repository\com\sun\jai\jai-core\resolver-status.properties
..
```

which could be a symptom for virus checkers etc. which hold a lock on windows systems...

furthermore i found in the Maven 2 log:

```
java.lang.NullPointerException: version was null for com.sun.jai:jai-codec
```

Apart from that i don't find the given dependency in any repository i have access to...Can reproduce this with an artifact which exists in a repository so i can try to reproduce this?

**Comment by jira-importer** [comment]
**[Marvin Lütgenau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=l%C3%BCtti)** commented

Hi,
it seems that the version of jai isn't avalible anymore in public repositories.
We created two example artifacts that you can copy into your local "../.m2/repository" folder for reproduction.

I did some more research and found out that it doesn't per se depent on the ranged version. The NPE occur if there is a circular dependency within a used artifact created by using ranged versions.

I also updated the example pom.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Works for me:

```
C:\Users\mosipov\Downloads>mvn dependency:tree  -Dincludes=:::*-SNAPSHOT -U
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building tree-npe 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ tree-npe ---
[INFO] dependency-issues:tree-npe:jar:1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.759 s
[INFO] Finished at: 2017-04-16T01:24:21+02:00
[INFO] Final Memory: 12M/241M
[INFO] ------------------------------------------------------------------------
```
